# Notebook 01 — ETL Pipeline — Student Version

## Goal

Build a **versioned, privacy-aware ML feature dataset** from the QBC12 Airbnb PostgreSQL database.

Final output:

- one row per `listing_id`
- one fixed `cutoff_date`
- features built only from data available before/on the cutoff
- target built from future calendar availability
- no raw PII columns in the final ML dataset

The next notebook will use this output for MLflow experiments. If this ETL is messy, the ML notebook will be garbage.

## What you must submit from this notebook

By the end, your notebook must save these files under `data/features/`:

```text
listing_availability_features_<version>.csv
listing_availability_features_<version>.parquet
listing_availability_features_<version>_metadata.json
listing_availability_features_<version>_validation_report.json
pii_audit_<version>.csv
```

The notebook must also show:

1. database connection check,
2. table/column inspection,
3. PII audit,
4. cutoff-date logic,
5. feature construction,
6. label construction,
7. validation checks.

## 0. Imports

These libraries are enough for the ETL notebook.

Install missing packages with:

```bash
pip install pandas numpy sqlalchemy psycopg2-binary pyarrow
```

In [49]:
import os
import json
import re
from pathlib import Path
from datetime import timedelta

import numpy as np
import pandas as pd

from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

## 1. Configuration

These values define the dataset version and the time windows.

- `PAST_WINDOW_DAYS`: how much history is used for features.
- `FUTURE_WINDOW_DAYS`: how much future data is used for the target.
- `HIGH_DEMAND_AVAILABLE_RATE_THRESHOLD`: the rule for the positive class.

If you change any of these, change `DATASET_VERSION`.

In [51]:
# -----------------------------
# ETL Configuration
# -----------------------------
DATASET_VERSION = "v1_student"

ENTITY_COLUMN = "listing_id"

PAST_WINDOW_DAYS = 90
FUTURE_WINDOW_DAYS = 30
HIGH_DEMAND_AVAILABLE_RATE_THRESHOLD = 0.30

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
DATA_DIR = PROJECT_ROOT / "data"
FEATURE_DIR = DATA_DIR / "features"

FEATURE_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("FEATURE_DIR:", FEATURE_DIR)

PROJECT_ROOT: C:\Users\sobhan\Downloads\HW_A
FEATURE_DIR: C:\Users\sobhan\Downloads\HW_A\data\features

## 2. Database connection

Use your assigned student database user.

The QBC12 database is:

host: 185.50.38.163

port: 32112

database: qbc12_airbnb

Important:

- Keep `sslmode=disable`.
- Do not commit real passwords to Git.

In [53]:
# -----------------------------
# Database Connection
# -----------------------------

# Clear old environment variables that may point to the wrong database.
# for key in ["PGHOST", "PGPORT", "PGDATABASE", "PGUSER", "PGPASSWORD"]:
#     os.environ.pop(key, None)

DB_HOST = os.getenv("PGHOST", "")
DB_PORT = int(os.getenv("PGPORT", ""))
DB_NAME = os.getenv("PGDATABASE", "")
DB_USER = os.getenv("PGUSER", "")
DB_PASSWORD = os.getenv("PGPASSWORD", "")


if DB_USER == "student_your_username" or DB_PASSWORD == "student_your_password":
    raise ValueError("Replace DB_USER and DB_PASSWORD with your assigned database credentials.")

print("Connecting to:")
print("HOST:", DB_HOST)
print("PORT:", DB_PORT)
print("DB:", DB_NAME)
print("USER:", DB_USER)

db_url = URL.create(
    drivername="postgresql+psycopg2",
    username=DB_USER,
    password=DB_PASSWORD,
    host=DB_HOST,
    port=DB_PORT,
    database=DB_NAME,
    query={"sslmode": "disable"},
)

engine = create_engine(db_url)

def read_sql(query: str, params: dict | None = None) -> pd.DataFrame:
    """Run a SQL query through SQLAlchemy and return a Pandas DataFrame."""
    with engine.connect() as conn:
        return pd.read_sql(text(query), conn, params=params)

with engine.connect() as conn:
    connection_check = conn.execute(
        text("""
        SELECT
            current_database() AS database,
            current_user AS user_name,
            inet_server_addr() AS server_ip,
            inet_server_port() AS server_port,
            now() AS checked_at;
        """)
    ).mappings().first()

dict(connection_check)

ValueError: invalid literal for int() with base 10: ''

In [55]:
import sys
!{sys.executable} -m pip install python-dotenv

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-dotenv in c:\programdata\anaconda3\lib\site-packages (0.21.0)

In [56]:
from dotenv import load_dotenv

In [57]:
from dotenv import load_dotenv
import os

load_dotenv(".env")

DB_HOST = os.getenv("DB_HOST", "")
DB_PORT = int(os.getenv("DB_PORT", "32112"))
DB_NAME = os.getenv("DB_NAME", "")
DB_USER = os.getenv("DB_USER", "")
DB_PASSWORD = os.getenv("DB_PASSWORD", "")

print("DB_HOST:", DB_HOST)
print("DB_PORT:", DB_PORT)
print("DB_NAME:", DB_NAME)
print("DB_USER:", DB_USER)
print("DB_PASSWORD loaded:", bool(DB_PASSWORD))

DB_HOST: 185.50.38.163
DB_PORT: 32112
DB_NAME: qbc12_airbnb
DB_USER: student_nazanin_hesari
DB_PASSWORD loaded: True

In [61]:
# -----------------------------
# Database Connection
# -----------------------------
import os
from dotenv import load_dotenv, find_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL
import pandas as pd

# Load .env file
load_dotenv(find_dotenv(usecwd=True))

DB_HOST = os.getenv("DB_HOST", "185.50.38.163")
DB_PORT = int(os.getenv("DB_PORT", "32112"))
DB_NAME = os.getenv("DB_NAME", "qbc12_airbnb")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")

if not DB_USER or not DB_PASSWORD:
    raise ValueError("DB_USER or DB_PASSWORD is not set. Check your .env file.")

print("Connecting to:")
print("HOST:", DB_HOST)
print("PORT:", DB_PORT)
print("DB:", DB_NAME)
print("USER:", DB_USER)
print("PASSWORD loaded:", bool(DB_PASSWORD))

db_url = URL.create(
    drivername="postgresql+psycopg2",
    username=DB_USER,
    password=DB_PASSWORD,
    host=DB_HOST,
    port=DB_PORT,
    database=DB_NAME,
    query={"sslmode": "disable"},
)

engine = create_engine(db_url)

def read_sql(query: str, params: dict | None = None) -> pd.DataFrame:
    with engine.connect() as conn:
        return pd.read_sql(text(query), conn, params=params)

with engine.connect() as conn:
    connection_check = conn.execute(
        text("""
        SELECT
            current_database() AS database,
            current_user AS user_name,
            inet_server_addr() AS server_ip,
            inet_server_port() AS server_port,
            now() AS checked_at;
        """)
    ).mappings().first()

dict(connection_check)

Connecting to:
HOST: 185.50.38.163
PORT: 32112
DB: qbc12_airbnb
USER: student_nazanin_hesari
PASSWORD loaded: True

{'database': 'qbc12_airbnb',
 'user_name': 'student_nazanin_hesari',
 'server_ip': '172.19.0.2',
 'server_port': 5432,
 'checked_at': datetime.datetime(2026, 5, 31, 13, 59, 28, 728660, tzinfo=datetime.timezone.utc)}

## 3. Inspect the available data

Before writing ETL, inspect the database.

You should confirm:

- which tables exist,
- which columns exist,
- how many rows each table has,
- whether important fields are missing.

In [63]:
tables_df = read_sql("""
SELECT
    table_schema,
    table_name,
    table_type
FROM information_schema.tables
WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
ORDER BY table_schema, table_name;
""")

tables_df

  table_schema     table_name  table_type
0         core   calendar_day  BASE TABLE
1         core           host  BASE TABLE
2         core        listing  BASE TABLE
3         core  neighbourhood  BASE TABLE
4         core         review  BASE TABLE

In [65]:
columns_df = read_sql("""
SELECT
    table_schema,
    table_name,
    ordinal_position,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_schema = 'core'
ORDER BY table_schema, table_name, ordinal_position;
""")

columns_df

,table_schema,table_name,ordinal_position,column_name,data_type,is_nullable
0,core,calendar_day,1,listing_id,bigint,NO
1,core,calendar_day,2,date,date,NO
2,core,calendar_day,3,available,boolean,YES
3,core,calendar_day,4,price,numeric,YES
4,core,calendar_day,5,adjusted_price,numeric,YES
5,core,calendar_day,6,minimum_nights,integer,YES
6,core,calendar_day,7,maximum_nights,integer,YES
7,core,host,1,host_id,bigint,NO
8,core,host,2,host_pseudo_id,text,NO
9,core,host,3,is_superhost,boolean,YES
10,core,listing,1,listing_id,bigint,NO
11,core,listing,2,host_id,bigint,NO
12,core,listing,3,neighbourhood_id,integer,YES
13,core,listing,4,room_type,text,YES
14,core,listing,5,property_type,text,YES
15,core,listing,6,accommodates,integer,YES
16,core,listing,7,bedrooms,numeric,YES
17,core,listing,8,beds,numeric,YES
18,core,listing,9,bathrooms_text,text,YES
19,core,listing,10,listing_price,numeric,YES
20,core,listing,11,minimum_nights,integer,YES
21,core,listing,12,maximum_nights,integer,YES
22,core,listing,13,instant_bookable,boolean,YES
23,core,listing,14,license,text,YES
24,core,neighbourhood,1,neighbourhood_id,integer,NO
25,core,neighbourhood,2,name,text,NO
26,core,review,1,review_id,bigint,NO
27,core,review,2,listing_id,bigint,NO
28,core,review,3,review_date,date,NO
29,core,review,4,reviewer_id,bigint,YES
30,core,review,5,reviewer_pseudo_id,text,YES
31,core,review,6,comment_len,integer,YES

In [67]:
row_counts_df = read_sql("""
SELECT 'core.calendar_day' AS table_name, COUNT(*) AS row_count FROM core.calendar_day
UNION ALL
SELECT 'core.host' AS table_name, COUNT(*) AS row_count FROM core.host
UNION ALL
SELECT 'core.listing' AS table_name, COUNT(*) AS row_count FROM core.listing
UNION ALL
SELECT 'core.neighbourhood' AS table_name, COUNT(*) AS row_count FROM core.neighbourhood
UNION ALL
SELECT 'core.review' AS table_name, COUNT(*) AS row_count FROM core.review
ORDER BY table_name;
""")

row_counts_df

           table_name  row_count
0   core.calendar_day    3825200
1           core.host       9201
2        core.listing      10480
3  core.neighbourhood         22
4         core.review     501084

## 4. Data quality audit

This step decides which columns are safe and useful.

You must check at least:

1. calendar date range,
2. review date range,
3. whether `calendar_day.price` and `adjusted_price` are usable,
4. whether recent review windows are meaningful.

Do not include columns that are all-null or nearly useless.

In [69]:
calendar_quality_df = read_sql("""
SELECT
    COUNT(*) AS n_rows,
    COUNT(*) FILTER (WHERE price IS NULL) AS null_price,
    COUNT(*) FILTER (WHERE adjusted_price IS NULL) AS null_adjusted_price,
    COUNT(*) FILTER (WHERE available IS NULL) AS null_available,
    MIN(date) AS min_calendar_date,
    MAX(date) AS max_calendar_date
FROM core.calendar_day;
""")

review_quality_df = read_sql("""
SELECT
    COUNT(*) AS n_rows,
    COUNT(*) FILTER (WHERE comment_len IS NULL) AS null_comment_len,
    MIN(review_date) AS min_review_date,
    MAX(review_date) AS max_review_date
FROM core.review;
""")

display(calendar_quality_df)
display(review_quality_df)

,n_rows,null_price,null_adjusted_price,null_available,min_calendar_date,max_calendar_date
0,3825200,3825200,3825200,0,2025-09-11,2026-09-10

   n_rows  null_comment_len min_review_date max_review_date
0  501084                 0      2010-08-22      2025-09-11

In [71]:
# Inspect small samples.
# Keep LIMIT small. Do not pull full raw calendar/review tables into Pandas.

for table_name in ["listing", "host", "neighbourhood", "review", "calendar_day"]:
    print(f"\n===== core.{table_name} =====")
    display(read_sql(f"SELECT * FROM core.{table_name} LIMIT 10;"))

===== core.listing =====

,listing_id,host_id,neighbourhood_id,room_type,property_type,accommodates,bedrooms,beds,bathrooms_text,listing_price,minimum_nights,maximum_nights,instant_bookable,license
0,27886,97647,2,Private room,Private room in houseboat,2,1.0,1.0,1.5 baths,132.0,3,356,False,0363 974D 4986 7411 88D8
1,28871,124245,2,Private room,Private room in rental unit,2,1.0,1.0,1 shared bath,89.0,2,730,False,0363 607B EA74 0BD8 2F6F
2,29051,124245,1,Private room,Private room in condo,2,1.0,1.0,1 shared bath,61.0,2,730,False,0363 607B EA74 0BD8 2F6F
3,44391,194779,1,Entire home/apt,Entire rental unit,4,2.0,NaN,1.5 baths,NaN,3,730,False,0363 E76E F06A C1DD 172C
4,48373,220434,8,Entire home/apt,Entire rental unit,4,2.0,NaN,1.5 baths,NaN,3,1125,False,0363 4A2B A6AD 0196 F684
5,49552,225987,2,Entire home/apt,Entire guest suite,3,2.0,2.0,1 bath,322.0,3,1125,False,0363 576A D827 5085 6B83
6,50263,230246,1,Entire home/apt,Entire condo,4,2.0,3.0,1.5 baths,457.0,2,14,False,0363 7F3D 0BAE 28C8 C7D2
7,50515,231864,14,Entire home/apt,Entire townhouse,5,3.0,3.0,1.5 baths,198.0,7,18,False,0363 5DDB E495 A6D5 CEC6
8,50523,231946,2,Entire home/apt,Entire condo,2,1.0,1.0,1 bath,162.0,2,365,False,0363 22DC 0E52 B70B 0FB8
9,53921,252245,10,Entire home/apt,Entire rental unit,3,1.0,NaN,1 bath,NaN,1,21,False,0363 B43C B1D4 2666 3739

===== core.host =====

     host_id                                     host_pseudo_id  is_superhost
0   27837566  12a252de05fbf2f7ba9f57fa3baa099acd17e2a9c7efc7...         False
1   12840373  d9f7e79668b99a5cb7963bfb2430d8b6b960a0ec4e82bb...         False
2  226859324  cc90d30412e286c0525c7914d031807c8c00e017fe1915...          True
3   20204265  755d79bf4be51df2d85792123200e6641db8589551965e...          True
4   47981094  b40c45156e81696746b6eb51ef86aeccff7c6d7cd5eac2...         False
5  443406859  cfe69dd56cffef559069b30216f8954b57e1de886b92a3...         False
6    2626085  43c4cdd7f1413364dd809c6c92c20baed35faa51f84e76...         False
7   74999205  1033d2369452b0969c1f63061af401f4581a92873b5659...          True
8    7969106  1b41831025e74b04a73fe88e99233d09f39660eac85bf6...         False
9    6127483  8cffc835ea5e24b102cf446e9d369edad9f3a2bf91bfbc...          True

===== core.neighbourhood =====

   neighbourhood_id                                    name
0                 1                            Centrum-Oost
1                 2                            Centrum-West
2                 3  Oostelijk Havengebied - Indische Buurt
3                 4                              Westerpark
4                 5                             Slotervaart
5                 6                         Bijlmer-Centrum
6                 7                 Geuzenveld - Slotermeer
7                 8                  Buitenveldert - Zuidas
8                 9                              Noord-West
9                10                IJburg - Zeeburgereiland

===== core.review =====

,review_id,listing_id,review_date,reviewer_id,reviewer_pseudo_id,comment_len
0,531281017,18062995,2019-09-17,73925523,2408ff6b678c0bdc30857dc6631d8762b57159ef9741c3...,392
1,531788922,18062995,2019-09-18,82572265,fb2e9dd6e8225de8231d388c9b9cf92b9c88f7e0823389...,13
2,532695264,18062995,2019-09-20,100595030,2503cafbac72a2a0a211282e2ed6e97c60058769ab3cf8...,467
3,537292491,18062995,2019-09-28,282542584,2612adccbea98416289b033feb314e33a3947244104fcf...,78
4,540324583,18062995,2019-10-03,116115856,7f6c33a5339d594d253c1aa0c9d5a2ae714321907af14c...,220
5,540880279,18062995,2019-10-04,65938182,b280baa9d72baf439c77b54c6ee11a42e4a9403fccec35...,145
6,542086221,18062995,2019-10-06,155392872,964cb3a74d1ccaaadd95915b842090390eed7754785aa5...,270
7,543734173,18062995,2019-10-08,52878420,5f477eaea2d8cd299828be54f31613eabe9e17072ff0bc...,204
8,544447121,18062995,2019-10-10,120972473,1314f5367fdcd67e16c7fb0828dad3be64be054d8042c2...,92
9,547826338,18062995,2019-10-16,31002341,6eedc8878c30f4380cbc920fd5ed63ff122aeba8f3bdf6...,91

===== core.calendar_day =====

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,792781586502433878,2026-04-19,False,None,None,2,30
1,792781586502433878,2026-04-20,False,None,None,2,30
2,792781586502433878,2026-04-21,False,None,None,2,30
3,792781586502433878,2026-04-22,False,None,None,2,30
4,792781586502433878,2026-04-23,False,None,None,2,30
5,792781586502433878,2026-04-24,False,None,None,2,30
6,792781586502433878,2026-04-25,False,None,None,2,30
7,792781586502433878,2026-04-26,False,None,None,2,30
8,792781586502433878,2026-04-27,False,None,None,2,30
9,792781586502433878,2026-04-28,False,None,None,2,30

In [73]:
columns_df = read_sql("""
SELECT
    table_name,
    ordinal_position,
    column_name,
    data_type
FROM information_schema.columns
WHERE table_schema = 'core'
  AND table_name = 'listing'
ORDER BY ordinal_position;
""")

columns_df

   table_name  ordinal_position       column_name data_type
0     listing                 1        listing_id    bigint
1     listing                 2           host_id    bigint
2     listing                 3  neighbourhood_id   integer
3     listing                 4         room_type      text
4     listing                 5     property_type      text
5     listing                 6      accommodates   integer
6     listing                 7          bedrooms   numeric
7     listing                 8              beds   numeric
8     listing                 9    bathrooms_text      text
9     listing                10     listing_price   numeric
10    listing                11    minimum_nights   integer
11    listing                12    maximum_nights   integer
12    listing                13  instant_bookable   boolean
13    listing                14           license      text

## 5. Choose the cutoff date

The cutoff separates features from the label.

Rules:

- Historical features use dates `history_start_date <= date <= cutoff_date`.
- The label uses dates `cutoff_date < date <= label_end_date`.
- The cutoff must have enough past calendar data and enough future calendar data.

For this homework, use a 90-day feature window and a 30-day label window.

In [75]:
range_df = read_sql("""
SELECT
    (SELECT MIN(date) FROM core.calendar_day) AS calendar_min_date,
    (SELECT MAX(date) FROM core.calendar_day) AS calendar_max_date,
    (SELECT MIN(review_date) FROM core.review) AS review_min_date,
    (SELECT MAX(review_date) FROM core.review) AS review_max_date;
""")

range_df

  calendar_min_date calendar_max_date review_min_date review_max_date
0        2025-09-11        2026-09-10      2010-08-22      2025-09-11

In [ ]:
calendar_min_date = pd.to_datetime(range_df.loc[0, "calendar_min_date"]).date()
calendar_max_date = pd.to_datetime(range_df.loc[0, "calendar_max_date"]).date()

# TODO:
# 1. Compute earliest valid cutoff using calendar_min_date and PAST_WINDOW_DAYS.
# 2. Compute latest valid cutoff using calendar_max_date and FUTURE_WINDOW_DAYS.
# 3. Choose a valid cutoff_date.
# 4. Compute history_start_date and label_end_date.
#
# Hint:
# earliest valid cutoff = calendar_min_date + PAST_WINDOW_DAYS
# latest valid cutoff = calendar_max_date - FUTURE_WINDOW_DAYS

earliest_cutoff_allowed_by_calendar = None  # TODO
latest_cutoff_allowed_by_calendar = None    # TODO

cutoff_date = None          # TODO
history_start_date = None   # TODO
label_end_date = None       # TODO

# TODO: print all dates and assert that the windows are valid.
raise NotImplementedError("TODO: implement cutoff-date logic.")

In [77]:
calendar_min_date = pd.to_datetime(range_df.loc[0, "calendar_min_date"]).date()
calendar_max_date = pd.to_datetime(range_df.loc[0, "calendar_max_date"]).date()

# 1. earliest valid cutoff
earliest_cutoff_allowed_by_calendar = calendar_min_date + timedelta(days=PAST_WINDOW_DAYS)
# 2. latest valid cutoff
latest_cutoff_allowed_by_calendar = calendar_max_date - timedelta(days=FUTURE_WINDOW_DAYS)

# 3. choose a cutoff — وسط بازه‌ی مجاز انتخاب امن و قابل تکراریه
cutoff_date = latest_cutoff_allowed_by_calendar   # نزدیک‌ترین cutoff که آینده‌ی کافی داره

# 4. compute history & label windows
history_start_date = cutoff_date - timedelta(days=PAST_WINDOW_DAYS)
label_end_date = cutoff_date + timedelta(days=FUTURE_WINDOW_DAYS)

print("calendar_min_date:", calendar_min_date)
print("calendar_max_date:", calendar_max_date)
print("earliest_cutoff_allowed:", earliest_cutoff_allowed_by_calendar)
print("latest_cutoff_allowed:", latest_cutoff_allowed_by_calendar)
print("cutoff_date:", cutoff_date)
print("history_start_date:", history_start_date)
print("label_end_date:", label_end_date)

assert cutoff_date >= earliest_cutoff_allowed_by_calendar, "Not enough past calendar data."
assert cutoff_date <= latest_cutoff_allowed_by_calendar, "Not enough future calendar data."
assert history_start_date >= calendar_min_date
assert label_end_date <= calendar_max_date
print("\nCutoff windows are valid ✅")

calendar_min_date: 2025-09-11
calendar_max_date: 2026-09-10
earliest_cutoff_allowed: 2025-12-10
latest_cutoff_allowed: 2026-08-11
cutoff_date: 2026-08-11
history_start_date: 2026-05-13
label_end_date: 2026-09-10

Cutoff windows are valid ✅

## 6. PII audit

Raw identifiers can be needed for joins, but they must not become model features.

Your final ML feature table must not contain:

- `host_id`
- `host_pseudo_id`
- `review_id`
- `reviewer_id`
- `reviewer_pseudo_id`
- `license`
- raw text fields that may contain sensitive information

`listing_id` may stay as an entity key, but it must be excluded from model inputs later.

In [ ]:
# TODO: complete the PII audit table.
# Add rows for all sensitive or identity-linking columns you find relevant.

pii_audit = pd.DataFrame([
    {
        "table": "listing",
        "column": "listing_id",
        "pii_type": "entity identifier",
        "decision": "keep as entity key only",
        "reason": "needed to define one row per listing; not a model input"
    },
    # TODO: add host_id
    # TODO: add host_pseudo_id
    # TODO: add license
    # TODO: add review_id
    # TODO: add reviewer_id
    # TODO: add reviewer_pseudo_id
])

pii_audit

In [79]:
pii_audit = pd.DataFrame([
    {"table": "listing", "column": "listing_id", "pii_type": "entity identifier",
     "decision": "keep as entity key only",
     "reason": "needed to define one row per listing; not a model input"},
    {"table": "listing", "column": "host_id", "pii_type": "direct identifier (host)",
     "decision": "drop from features (use only for join)",
     "reason": "links listing to a real person; not allowed as model input"},
    {"table": "host", "column": "host_pseudo_id", "pii_type": "pseudonymous identifier",
     "decision": "drop from features (join only)",
     "reason": "still re-identifies a host across listings"},
    {"table": "listing", "column": "license", "pii_type": "regulatory/legal identifier",
     "decision": "drop",
     "reason": "may contain government license numbers; sensitive & high-missing"},
    {"table": "review", "column": "review_id", "pii_type": "record identifier",
     "decision": "drop (aggregate only)",
     "reason": "row-level identifier, not a meaningful feature"},
    {"table": "review", "column": "reviewer_id", "pii_type": "direct identifier (reviewer)",
     "decision": "drop (aggregate to counts only)",
     "reason": "identifies a real reviewer"},
    {"table": "review", "column": "reviewer_pseudo_id", "pii_type": "pseudonymous identifier",
     "decision": "drop (count distinct only)",
     "reason": "re-identifies reviewers across reviews"},
])

pii_audit

,table,column,pii_type,decision,reason
0,listing,listing_id,entity identifier,keep as entity key only,needed to define one row per listing; not a mo...
1,listing,host_id,direct identifier (host),drop from features (use only for join),links listing to a real person; not allowed as...
2,host,host_pseudo_id,pseudonymous identifier,drop from features (join only),still re-identifies a host across listings
3,listing,license,regulatory/legal identifier,drop,may contain government license numbers; sensit...
4,review,review_id,record identifier,drop (aggregate only),"row-level identifier, not a meaningful feature"
5,review,reviewer_id,direct identifier (reviewer),drop (aggregate to counts only),identifies a real reviewer
6,review,reviewer_pseudo_id,pseudonymous identifier,drop (count distinct only),re-identifies reviewers across reviews

## 7. Extract static tables

`listing`, `host`, and `neighbourhood` are small enough to load directly.

Do not load full `review` or `calendar_day` into Pandas. Those must be aggregated in SQL later.

In [ ]:
# TODO: write SQL to load the required listing columns.
listing_df = read_sql("""
SELECT
    -- TODO: select only needed columns
FROM core.listing;
""")

# TODO: write SQL to load host columns.
host_df = read_sql("""
SELECT
    -- TODO: select only needed columns
FROM core.host;
""")

# TODO: write SQL to load neighbourhood columns.
neighbourhood_df = read_sql("""
SELECT
    -- TODO: select needed columns and rename name to neighbourhood_name
FROM core.neighbourhood;
""")

print("listing:", listing_df.shape)
print("host:", host_df.shape)
print("neighbourhood:", neighbourhood_df.shape)

In [82]:
def get_table_columns(table_name: str) -> list[str]:
    df = read_sql("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_schema = 'core'
      AND table_name = :table_name
    ORDER BY ordinal_position;
    """, params={"table_name": table_name})
    return df["column_name"].tolist()

In [84]:
listing_df = read_sql("""
SELECT
    listing_id,
    host_id,
    neighbourhood_id,
    room_type,
    property_type,
    accommodates,
    bedrooms,
    beds,
    bathrooms_text,
    listing_price,
    minimum_nights,
    maximum_nights,
    instant_bookable,
    license
FROM core.listing;
""")

# -----------------------------
# Host table: select only existing columns
# -----------------------------
host_cols = get_table_columns("host")
desired_host_cols = [
    "host_id",
    "host_pseudo_id",
    "is_superhost",
    "host_response_rate",
    "host_acceptance_rate",
]

existing_host_cols = [c for c in desired_host_cols if c in host_cols]

if "host_id" not in existing_host_cols:
    raise ValueError("host_id does not exist in core.host, cannot join host table.")

host_query = f"""
SELECT
    {", ".join(existing_host_cols)}
FROM core.host;
"""

host_df = read_sql(host_query)


# -----------------------------
# Neighbourhood table: select only existing columns
# -----------------------------
neighbourhood_cols = get_table_columns("neighbourhood")

neighbourhood_select_parts = []

if "neighbourhood_id" in neighbourhood_cols:
    neighbourhood_select_parts.append("neighbourhood_id")
else:
    raise ValueError("neighbourhood_id does not exist in core.neighbourhood.")

if "name" in neighbourhood_cols:
    neighbourhood_select_parts.append("name AS neighbourhood_name")

if "neighbourhood_group" in neighbourhood_cols:
    neighbourhood_select_parts.append("neighbourhood_group")

neighbourhood_query = f"""
SELECT
    {", ".join(neighbourhood_select_parts)}
FROM core.neighbourhood;
"""

neighbourhood_df = read_sql(neighbourhood_query)

print("listing:", listing_df.shape)
print("host:", host_df.shape, host_df.columns.tolist())
print("neighbourhood:", neighbourhood_df.shape, neighbourhood_df.columns.tolist())

listing: (10480, 14)
host: (9201, 3) ['host_id', 'host_pseudo_id', 'is_superhost']
neighbourhood: (22, 2) ['neighbourhood_id', 'neighbourhood_name']

## 8. Clean static fields

Convert database values into ML-friendly columns.

Required work:

- convert booleans to boolean dtype,
- convert numeric listing columns to numeric dtype,
- parse `bathrooms_text` into a numeric `bathrooms` feature.

In [ ]:
# TODO: normalize boolean columns.
# Example target columns:
# - listing_df["instant_bookable"]
# - host_df["is_superhost"]

# TODO: normalize numeric listing columns.
numeric_cols_listing = [
    "accommodates",
    "bedrooms",
    "beds",
    "listing_price",
    "minimum_nights",
    "maximum_nights",
]

for col in numeric_cols_listing:
    # TODO
    pass


def parse_bathrooms(text_value):
    """
    Convert bathrooms_text into a number.

    Examples:
    - '1 bath' -> 1.0
    - '1.5 baths' -> 1.5
    - 'Half-bath' -> 0.5
    - missing/unrecognized -> NaN
    """
    # TODO: implement parser.
    raise NotImplementedError("TODO: implement parse_bathrooms")


listing_df["bathrooms"] = listing_df["bathrooms_text"].apply(parse_bathrooms)

listing_df[["bathrooms_text", "bathrooms"]].head(10)

In [86]:
def to_bool(s):
    return (
        s.astype(str).str.strip().str.lower()
        .map({"t": True, "true": True, "1": True, "yes": True,
              "f": False, "false": False, "0": False, "no": False})
        .astype("boolean")
    )

# instant_bookable خودش boolean بود (طبق اسکیما)
if "instant_bookable" in listing_df.columns and listing_df["instant_bookable"].dtype not in ("boolean", bool):
    listing_df["instant_bookable"] = to_bool(listing_df["instant_bookable"])

# is_superhost: ممکنه bool یا text باشه — امن نرمالایز می‌کنیم
if "is_superhost" in host_df.columns and host_df["is_superhost"].dtype not in ("boolean", bool):
    host_df["is_superhost"] = to_bool(host_df["is_superhost"])

numeric_cols_listing = ["accommodates", "bedrooms", "beds",
                        "listing_price", "minimum_nights", "maximum_nights"]
for col in numeric_cols_listing:
    if col in listing_df.columns:
        listing_df[col] = pd.to_numeric(listing_df[col], errors="coerce")


def parse_bathrooms(text_value):
    if text_value is None or (isinstance(text_value, float) and np.isnan(text_value)):
        return np.nan
    s = str(text_value).strip().lower()
    if s in ("", "nan"):
        return np.nan
    if "half" in s:
        return 0.5
    m = re.search(r"(\d+(\.\d+)?)", s)
    return float(m.group(1)) if m else np.nan


listing_df["bathrooms"] = listing_df["bathrooms_text"].apply(parse_bathrooms)
listing_df[["bathrooms_text", "bathrooms"]].head(10)

  bathrooms_text  bathrooms
0      1.5 baths        1.5
1  1 shared bath        1.0
2  1 shared bath        1.0
3      1.5 baths        1.5
4      1.5 baths        1.5
5         1 bath        1.0
6      1.5 baths        1.5
7      1.5 baths        1.5
8         1 bath        1.0
9         1 bath        1.0

## 9. Build static listing features

Join:

- `listing` → `host`
- `listing` → `neighbourhood`
- host-level aggregate `host_listing_count`

Final static features should be one row per `listing_id`.

Do not keep raw `host_id`, `host_pseudo_id`, `neighbourhood_id`, `license`, or `bathrooms_text` in the final static feature table.

In [ ]:
# TODO: create host_listing_features with one row per host_id.
host_listing_features = None

# TODO: merge listing, host, host_listing_features, and neighbourhood.
base_listing_features = None

# TODO: choose privacy-safe static feature columns.
static_feature_cols = [
    "listing_id",
    # TODO
]

static_features = base_listing_features[static_feature_cols].copy()

assert static_features["listing_id"].duplicated().sum() == 0

print(static_features.shape)
static_features.head()

In [88]:
host_listing_features = (
    listing_df.groupby("host_id")["listing_id"]
    .nunique()
    .reset_index(name="host_listing_count")
)

base_listing_features = (
    listing_df
    .merge(host_df, on="host_id", how="left")
    .merge(host_listing_features, on="host_id", how="left")
    .merge(neighbourhood_df, on="neighbourhood_id", how="left")
)

# فقط فیچرهایی که واقعاً موجودن — host_response_rate / acceptance_rate / neighbourhood_group حذف می‌شن
static_feature_cols = [
    "listing_id",
    "room_type",
    "property_type",
    "accommodates",
    "bedrooms",
    "beds",
    "bathrooms",
    "listing_price",
    "minimum_nights",
    "maximum_nights",
    "instant_bookable",
    "is_superhost",
    "host_response_rate",       # وجود نداره → فیلتر می‌شه
    "host_acceptance_rate",     # وجود نداره → فیلتر می‌شه
    "host_listing_count",
    "neighbourhood_name",
    "neighbourhood_group",      # وجود نداره → فیلتر می‌شه
]
static_feature_cols = [c for c in static_feature_cols if c in base_listing_features.columns]

static_features = base_listing_features[static_feature_cols].copy()
assert static_features["listing_id"].duplicated().sum() == 0
print(static_features.shape)
print("Selected columns:", static_feature_cols)
static_features.head()

(10480, 14)
Selected columns: ['listing_id', 'room_type', 'property_type', 'accommodates', 'bedrooms', 'beds', 'bathrooms', 'listing_price', 'minimum_nights', 'maximum_nights', 'instant_bookable', 'is_superhost', 'host_listing_count', 'neighbourhood_name']

,listing_id,room_type,property_type,accommodates,bedrooms,beds,bathrooms,listing_price,minimum_nights,maximum_nights,instant_bookable,is_superhost,host_listing_count,neighbourhood_name
0,27886,Private room,Private room in houseboat,2,1.0,1.0,1.5,132.0,3,356,False,True,1,Centrum-West
1,28871,Private room,Private room in rental unit,2,1.0,1.0,1.0,89.0,2,730,False,True,2,Centrum-West
2,29051,Private room,Private room in condo,2,1.0,1.0,1.0,61.0,2,730,False,True,2,Centrum-Oost
3,44391,Entire home/apt,Entire rental unit,4,2.0,NaN,1.5,NaN,3,730,False,False,1,Centrum-Oost
4,48373,Entire home/apt,Entire rental unit,4,2.0,NaN,1.5,NaN,3,1125,False,False,1,Buitenveldert - Zuidas

## 10. Build review features in SQL

Do not load raw `core.review` into Pandas.

Build one row per listing in SQL.

Required output columns:

- `listing_id`
- `total_reviews_before_cutoff`
- `unique_reviewers_before_cutoff`
- `avg_comment_len_before_cutoff`
- `max_comment_len_before_cutoff`
- `days_since_last_review`

Use only reviews where `review_date <= cutoff_date`.

In [90]:
tables_df = read_sql("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'core'
ORDER BY table_name;
""")
tables_df

      table_name
0   calendar_day
1           host
2        listing
3  neighbourhood
4         review

In [92]:
read_sql("""
SELECT table_name, ordinal_position, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'core'
  AND table_name IN ('review', 'calendar', 'calendar_day', 'calendar_30')
ORDER BY table_name, ordinal_position;
""")

      table_name  ordinal_position         column_name data_type
0   calendar_day                 1          listing_id    bigint
1   calendar_day                 2                date      date
2   calendar_day                 3           available   boolean
3   calendar_day                 4               price   numeric
4   calendar_day                 5      adjusted_price   numeric
5   calendar_day                 6      minimum_nights   integer
6   calendar_day                 7      maximum_nights   integer
7         review                 1           review_id    bigint
8         review                 2          listing_id    bigint
9         review                 3         review_date      date
10        review                 4         reviewer_id    bigint
11        review                 5  reviewer_pseudo_id      text
12        review                 6         comment_len   integer

In [ ]:
# TODO: write SQL aggregation over core.review.
# Use CAST(:cutoff_date AS date) when using the cutoff inside SQL.

review_features = read_sql(
    """
    SELECT
        listing_id
        -- TODO: aggregate review features
    FROM core.review
    WHERE review_date <= CAST(:cutoff_date AS date)
    GROUP BY listing_id;
    """,
    params={"cutoff_date": cutoff_date},
)

# TODO: convert feature columns to numeric where needed.

assert review_features["listing_id"].duplicated().sum() == 0

print(review_features.shape)
review_features.head()

In [94]:
review_features = read_sql(
    """
    SELECT
        listing_id,
        COUNT(*)                                    AS total_reviews_before_cutoff,
        COUNT(DISTINCT reviewer_id)                 AS unique_reviewers_before_cutoff,
        AVG(comment_len)                            AS avg_comment_len_before_cutoff,
        MAX(comment_len)                            AS max_comment_len_before_cutoff,
        (CAST(:cutoff_date AS date) - MAX(review_date)) AS days_since_last_review
    FROM core.review
    WHERE review_date <= CAST(:cutoff_date AS date)
    GROUP BY listing_id;
    """,
    params={"cutoff_date": cutoff_date},
)

num_cols = ["total_reviews_before_cutoff", "unique_reviewers_before_cutoff",
            "avg_comment_len_before_cutoff", "max_comment_len_before_cutoff",
            "days_since_last_review"]
for c in num_cols:
    review_features[c] = pd.to_numeric(review_features[c], errors="coerce")

assert review_features["listing_id"].duplicated().sum() == 0
print(review_features.shape)
review_features.head()

(9383, 6)

,listing_id,total_reviews_before_cutoff,unique_reviewers_before_cutoff,avg_comment_len_before_cutoff,max_comment_len_before_cutoff,days_since_last_review
0,27886,311,311,302.167203,1917,338
1,28871,732,729,201.236339,1265,338
2,29051,849,841,245.108363,2253,337
3,44391,42,42,242.309524,891,1452
4,48373,5,5,272.200000,949,835

## 11. Build calendar history features in SQL

Do not load raw `core.calendar_day` into Pandas.

Build historical availability features using:

- 90-day history window,
- 30-day recent history window.

Do not include calendar price features unless your audit proves they are usable.

In [ ]:
# TODO: write SQL aggregation over core.calendar_day.
# Use history_start_date and cutoff_date.
#
# Required output examples:
# - available_days_last_90d
# - available_rate_last_90d
# - avg_minimum_nights_calendar_last_90d
# - avg_maximum_nights_calendar_last_90d
# - available_days_last_30d
# - available_rate_last_30d
# - avg_minimum_nights_calendar_last_30d
# - avg_maximum_nights_calendar_last_30d

calendar_features_all = read_sql(
    """
    SELECT
        listing_id
        -- TODO: aggregate calendar history features
    FROM core.calendar_day
    WHERE date >= CAST(:history_start_date AS date)
      AND date <= CAST(:cutoff_date AS date)
    GROUP BY listing_id;
    """,
    params={
        "history_start_date": history_start_date,
        "cutoff_date": cutoff_date,
    },
)

# TODO: convert numeric columns.

assert calendar_features_all["listing_id"].duplicated().sum() == 0

print(calendar_features_all.shape)
calendar_features_all.head()

In [96]:
calendar_features_all = read_sql(
    """
    SELECT
        listing_id,
        -- full history window (history_start .. cutoff)
        SUM(CASE WHEN available THEN 1 ELSE 0 END)            AS available_days_history,
        AVG(CASE WHEN available THEN 1.0 ELSE 0.0 END)        AS available_rate_history,
        AVG(price)                                            AS avg_price_history,
        AVG(minimum_nights)                                   AS avg_minimum_nights_calendar_history,
        AVG(maximum_nights)                                   AS avg_maximum_nights_calendar_history,
        COUNT(*)                                              AS calendar_days_observed_history,

        -- last 30 days before cutoff
        SUM(CASE WHEN date > CAST(:cutoff_date AS date) - INTERVAL '30 days'
                  AND available THEN 1 ELSE 0 END)            AS available_days_last_30d,
        AVG(CASE WHEN date > CAST(:cutoff_date AS date) - INTERVAL '30 days'
                 THEN (CASE WHEN available THEN 1.0 ELSE 0.0 END) END)
                                                              AS available_rate_last_30d,
        AVG(CASE WHEN date > CAST(:cutoff_date AS date) - INTERVAL '30 days'
                 THEN price END)                              AS avg_price_last_30d
    FROM core.calendar_day
    WHERE date >= CAST(:history_start_date AS date)
      AND date <= CAST(:cutoff_date AS date)
    GROUP BY listing_id;
    """,
    params={"history_start_date": history_start_date, "cutoff_date": cutoff_date},
)

for c in calendar_features_all.columns:
    if c != "listing_id":
        calendar_features_all[c] = pd.to_numeric(calendar_features_all[c], errors="coerce")

assert calendar_features_all["listing_id"].duplicated().sum() == 0
print(calendar_features_all.shape)
calendar_features_all.head()

(10480, 10)

,listing_id,available_days_history,available_rate_history,avg_price_history,avg_minimum_nights_calendar_history,avg_maximum_nights_calendar_history,calendar_days_observed_history,available_days_last_30d,available_rate_last_30d,avg_price_last_30d
0,27886,0,0.000000,NaN,3.0,30.0,91,0,0.000000,NaN
1,28871,46,0.505495,NaN,2.0,730.0,91,14,0.466667,NaN
2,29051,43,0.472527,NaN,2.0,730.0,91,16,0.533333,NaN
3,44391,0,0.000000,NaN,3.0,730.0,91,0,0.000000,NaN
4,48373,0,0.000000,NaN,3.0,1125.0,91,0,0.000000,NaN

## 12. Build the target label

The label is built from future calendar availability.

Positive class:

```text
high_demand_proxy = 1 if future_available_rate_30d <= 0.30
```

This is not confirmed booking demand. It is a low-availability proxy.

In [ ]:
# TODO: write SQL to build one label row per listing.
# Use only dates after cutoff_date and up to label_end_date.

label_df = read_sql(
    """
    SELECT
        listing_id
        -- TODO: future_calendar_days_observed_30d
        -- TODO: future_available_days_30d
        -- TODO: future_available_rate_30d
        -- TODO: high_demand_proxy
    FROM core.calendar_day
    WHERE date > CAST(:cutoff_date AS date)
      AND date <= CAST(:label_end_date AS date)
    GROUP BY listing_id;
    """,
    params={
        "cutoff_date": cutoff_date,
        "label_end_date": label_end_date,
        "threshold": HIGH_DEMAND_AVAILABLE_RATE_THRESHOLD,
    },
)

# TODO: convert numeric columns and make high_demand_proxy integer.

assert label_df["listing_id"].duplicated().sum() == 0

print(label_df.shape)
label_df.head()

In [98]:
label_df = read_sql(
    """
    SELECT
        listing_id,
        COUNT(*)                                       AS future_calendar_days_observed_30d,
        SUM(CASE WHEN available THEN 1 ELSE 0 END)      AS future_available_days_30d,
        AVG(CASE WHEN available THEN 1.0 ELSE 0.0 END)  AS future_available_rate_30d,
        CASE
            WHEN AVG(CASE WHEN available THEN 1.0 ELSE 0.0 END) <= :threshold
            THEN 1 ELSE 0
        END                                            AS high_demand_proxy
    FROM core.calendar_day
    WHERE date > CAST(:cutoff_date AS date)
      AND date <= CAST(:label_end_date AS date)
    GROUP BY listing_id;
    """,
    params={
        "cutoff_date": cutoff_date,
        "label_end_date": label_end_date,
        "threshold": HIGH_DEMAND_AVAILABLE_RATE_THRESHOLD,
    },
)

for c in ["future_calendar_days_observed_30d", "future_available_days_30d",
          "future_available_rate_30d"]:
    label_df[c] = pd.to_numeric(label_df[c], errors="coerce")
label_df["high_demand_proxy"] = label_df["high_demand_proxy"].astype(int)

assert label_df["listing_id"].duplicated().sum() == 0
print(label_df.shape)
print(label_df["high_demand_proxy"].value_counts())
label_df.head()

(10480, 5)
high_demand_proxy
1    7994
0    2486
Name: count, dtype: int64

,listing_id,future_calendar_days_observed_30d,future_available_days_30d,future_available_rate_30d,high_demand_proxy
0,1443670960781261954,30,30,1.0,0
1,896043282611946316,30,0,0.0,1
2,39969190,30,0,0.0,1
3,958726726744532841,30,0,0.0,1
4,1272264495001498383,30,30,1.0,0

In [100]:
# Check label balance.

label_distribution = (
    label_df["high_demand_proxy"]
    .value_counts(dropna=False)
    .rename_axis("high_demand_proxy")
    .reset_index(name="count")
)

label_distribution["percentage"] = (
    label_distribution["count"] / label_distribution["count"].sum()
).round(4)

label_distribution

   high_demand_proxy  count  percentage
0                  1   7994      0.7628
1                  0   2486      0.2372

## 13. Join feature groups and label

Join all feature groups into one ML-ready table.

The final granularity must be:

```text
one row = one listing_id at one cutoff_date
```

Use an inner join with `label_df`, because rows without a target cannot be used for supervised learning.

In [ ]:
# TODO: join static_features, review_features, calendar_features_all, and label_df.
feature_df = None

# TODO: add cutoff_date and dataset_version columns.
# TODO: fill missing review count features with zero.
# TODO: handle missing days_since_last_review for listings with no reviews.

assert feature_df["listing_id"].duplicated().sum() == 0

print(feature_df.shape)
feature_df.head()

In [102]:
feature_df = (
    static_features
    .merge(review_features, on="listing_id", how="left")
    .merge(calendar_features_all, on="listing_id", how="left")
    .merge(label_df, on="listing_id", how="inner")   # فقط ردیف‌هایی که target دارن
)

feature_df["cutoff_date"] = pd.to_datetime(cutoff_date)
feature_df["dataset_version"] = DATASET_VERSION

# review counts: missing => 0
for c in ["total_reviews_before_cutoff", "unique_reviewers_before_cutoff"]:
    if c in feature_df.columns:
        feature_df[c] = feature_df[c].fillna(0)

# listingهای بدون review: days_since_last_review را با عدد بزرگ پر کن + flag
if "days_since_last_review" in feature_df.columns:
    big = (cutoff_date - calendar_min_date).days + PAST_WINDOW_DAYS
    feature_df["has_reviews"] = (feature_df["total_reviews_before_cutoff"] > 0).astype(int)
    feature_df["days_since_last_review"] = feature_df["days_since_last_review"].fillna(big)

assert feature_df["listing_id"].duplicated().sum() == 0
print(feature_df.shape)
feature_df.head()

(10480, 35)

,listing_id,room_type,property_type,accommodates,bedrooms,beds,bathrooms,listing_price,minimum_nights,maximum_nights,...,available_days_last_30d,available_rate_last_30d,avg_price_last_30d,future_calendar_days_observed_30d,future_available_days_30d,future_available_rate_30d,high_demand_proxy,cutoff_date,dataset_version,has_reviews
0,27886,Private room,Private room in houseboat,2,1.0,1.0,1.5,132.0,3,356,...,0,0.000000,NaN,30,0,0.0,1,2026-08-11,v1_student,1
1,28871,Private room,Private room in rental unit,2,1.0,1.0,1.0,89.0,2,730,...,14,0.466667,NaN,30,21,0.7,0,2026-08-11,v1_student,1
2,29051,Private room,Private room in condo,2,1.0,1.0,1.0,61.0,2,730,...,16,0.533333,NaN,30,0,0.0,1,2026-08-11,v1_student,1
3,44391,Entire home/apt,Entire rental unit,4,2.0,NaN,1.5,NaN,3,730,...,0,0.000000,NaN,30,0,0.0,1,2026-08-11,v1_student,1
4,48373,Entire home/apt,Entire rental unit,4,2.0,NaN,1.5,NaN,3,1125,...,0,0.000000,NaN,30,0,0.0,1,2026-08-11,v1_student,1

## 14. Drop unusable columns

Before saving, remove bad feature columns.

Drop columns that are:

- more than 95% missing,
- constant across all rows,

but protect target/audit columns.

In [104]:
protected_columns = {
    "listing_id",
    "cutoff_date",
    "dataset_version",
    "future_calendar_days_observed_30d",
    "future_available_days_30d",
    "future_available_rate_30d",
    "high_demand_proxy",
}

HIGH_MISSING_DROP_THRESHOLD = 0.95

# TODO: compute missing rates.
# TODO: find high-missing columns outside protected columns.
# TODO: find constant columns outside protected columns.
# TODO: drop them from feature_df.

columns_to_drop = []  # TODO

print("Columns to drop:", columns_to_drop)

feature_df = feature_df.drop(columns=columns_to_drop)

print("New shape:", feature_df.shape)

Columns to drop: []
New shape: (10480, 35)

In [106]:
protected_columns = {
    "listing_id", "cutoff_date", "dataset_version",
    "future_calendar_days_observed_30d", "future_available_days_30d",
    "future_available_rate_30d", "high_demand_proxy",
}
HIGH_MISSING_DROP_THRESHOLD = 0.95

missing_rates = feature_df.isna().mean()
high_missing = [c for c in feature_df.columns
                if c not in protected_columns and missing_rates[c] > HIGH_MISSING_DROP_THRESHOLD]

constant_cols = [c for c in feature_df.columns
                 if c not in protected_columns and feature_df[c].nunique(dropna=False) <= 1]

columns_to_drop = sorted(set(high_missing) | set(constant_cols))
print("Columns to drop:", columns_to_drop)

feature_df = feature_df.drop(columns=columns_to_drop)
print("New shape:", feature_df.shape)

Columns to drop: ['avg_price_history', 'avg_price_last_30d', 'calendar_days_observed_history']
New shape: (10480, 32)

## 15. Validate the final dataset

The validation step is mandatory.

Check:

1. no duplicate `listing_id + cutoff_date`,
2. target exists and is binary,
3. no missing target values,
4. no forbidden PII columns,
5. no future leakage columns in model inputs.

In [108]:
target_and_future_cols = {
    "high_demand_proxy",
    "future_available_rate_30d",
    "future_available_days_30d",
    "future_calendar_days_observed_30d",
}
id_and_meta_cols = {"listing_id", "cutoff_date", "dataset_version"}

model_input_columns = [
    c for c in feature_df.columns
    if c not in target_and_future_cols and c not in id_and_meta_cols
]
print("Model input columns:", model_input_columns)

Model input columns: ['room_type', 'property_type', 'accommodates', 'bedrooms', 'beds', 'bathrooms', 'listing_price', 'minimum_nights', 'maximum_nights', 'instant_bookable', 'is_superhost', 'host_listing_count', 'neighbourhood_name', 'total_reviews_before_cutoff', 'unique_reviewers_before_cutoff', 'avg_comment_len_before_cutoff', 'max_comment_len_before_cutoff', 'days_since_last_review', 'available_days_history', 'available_rate_history', 'avg_minimum_nights_calendar_history', 'avg_maximum_nights_calendar_history', 'available_days_last_30d', 'available_rate_last_30d', 'has_reviews']

In [110]:
duplicate_count = feature_df.duplicated(subset=["listing_id", "cutoff_date"]).sum()
missing_target_count = feature_df["high_demand_proxy"].isna().sum()
unique_target_values = sorted(feature_df["high_demand_proxy"].dropna().unique().tolist())

forbidden_columns = {
    "host_id",
    "host_pseudo_id",
    "reviewer_id",
    "reviewer_pseudo_id",
    "review_id",
    "license",
    "bathrooms_text",
}

present_forbidden_columns = sorted(forbidden_columns.intersection(feature_df.columns))

label_only_columns = [
    "future_calendar_days_observed_30d",
    "future_available_days_30d",
    "future_available_rate_30d",
    "high_demand_proxy",
]

model_input_columns = [
    col for col in feature_df.columns
    if col not in label_only_columns
    and col not in ["listing_id", "cutoff_date", "dataset_version"]
]

future_leakage_columns = [
    col for col in model_input_columns
    if col.startswith("future_")
]

# TODO: add asserts for each validation rule.
# for example:
# assert duplicate_count == 0

print("duplicate_count:", duplicate_count)
print("missing_target_count:", missing_target_count)
print("unique_target_values:", unique_target_values)
print("present_forbidden_columns:", present_forbidden_columns)
print("future_leakage_columns:", future_leakage_columns)
print("model_input_column_count:", len(model_input_columns))

duplicate_count: 0
missing_target_count: 0
unique_target_values: [0, 1]
present_forbidden_columns: []
future_leakage_columns: []
model_input_column_count: 25

In [112]:
missing_report = (
    feature_df
    .isna()
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

missing_report.columns = ["column", "missing_rate"]

calendar_coverage_summary = (
    feature_df[["future_calendar_days_observed_30d"]]
    .describe()
    .reset_index()
)

display(missing_report.head(30))
display(label_distribution)
display(calendar_coverage_summary)

                                 column  missing_rate
0                         listing_price      0.439504
1                                  beds      0.436641
2         avg_comment_len_before_cutoff      0.104676
3         max_comment_len_before_cutoff      0.104676
4                              bedrooms      0.029198
5                          is_superhost      0.010973
6                             bathrooms      0.001145
7     future_calendar_days_observed_30d      0.000000
8   avg_minimum_nights_calendar_history      0.000000
9   avg_maximum_nights_calendar_history      0.000000
10              available_days_last_30d      0.000000
11              available_rate_last_30d      0.000000
12            future_available_rate_30d      0.000000
13            future_available_days_30d      0.000000
14               available_days_history      0.000000
15                    high_demand_proxy      0.000000
16                          cutoff_date      0.000000
17                      dataset_version      0.000000
18               available_rate_history      0.000000
19                           listing_id      0.000000
20               days_since_last_review      0.000000
21                            room_type      0.000000
22       unique_reviewers_before_cutoff      0.000000
23          total_reviews_before_cutoff      0.000000
24                   neighbourhood_name      0.000000
25                   host_listing_count      0.000000
26                     instant_bookable      0.000000
27                       maximum_nights      0.000000
28                       minimum_nights      0.000000
29                         accommodates      0.000000

   high_demand_proxy  count  percentage
0                  1   7994      0.7628
1                  0   2486      0.2372

   index  future_calendar_days_observed_30d
0  count                            10480.0
1   mean                               30.0
2    std                                0.0
3    min                               30.0
4    25%                               30.0
5    50%                               30.0
6    75%                               30.0
7    max                               30.0

## 16. Save versioned outputs

Save:

- feature dataset,
- metadata,
- validation report,
- PII audit.

The MLflow notebook must read this output instead of querying raw database tables again.

In [114]:
csv_path = FEATURE_DIR / f"listing_availability_features_{DATASET_VERSION}.csv"
parquet_path = FEATURE_DIR / f"listing_availability_features_{DATASET_VERSION}.parquet"
metadata_path = FEATURE_DIR / f"listing_availability_features_{DATASET_VERSION}_metadata.json"
validation_path = FEATURE_DIR / f"listing_availability_features_{DATASET_VERSION}_validation_report.json"
pii_audit_path = FEATURE_DIR / f"pii_audit_{DATASET_VERSION}.csv"

feature_df.to_csv(csv_path, index=False)
print("Saved CSV:", csv_path)

try:
    feature_df.to_parquet(parquet_path, index=False)
    print("Saved Parquet:", parquet_path)
except ImportError:
    print("Parquet not saved because pyarrow/fastparquet is not installed.")
    print("Install pyarrow with: pip install pyarrow")

# TODO: build metadata dictionary.
metadata = {
    "dataset_version": DATASET_VERSION,
    "entity_column": ENTITY_COLUMN,
    # TODO: add cutoff, windows, source tables, target definition, exclusion rules
}

with open(metadata_path, "w", encoding="utf-8") as f:
    json.dump(metadata, f, indent=2, ensure_ascii=False)

# TODO: build validation_report dictionary.
validation_report = {
    "duplicate_listing_cutoff_rows": int(duplicate_count),
    "missing_target_count": int(missing_target_count),
    "target_values": unique_target_values,
    "present_forbidden_columns": present_forbidden_columns,
    "future_leakage_columns_in_model_inputs": future_leakage_columns,
    # TODO: add missing_report, label_distribution, calendar_coverage_summary
}

with open(validation_path, "w", encoding="utf-8") as f:
    json.dump(validation_report, f, indent=2, ensure_ascii=False)

pii_audit.to_csv(pii_audit_path, index=False)

print("Saved metadata:", metadata_path)
print("Saved validation report:", validation_path)
print("Saved PII audit:", pii_audit_path)

Saved CSV: C:\Users\sobhan\Downloads\HW_A\data\features\listing_availability_features_v1_student.csv
Saved Parquet: C:\Users\sobhan\Downloads\HW_A\data\features\listing_availability_features_v1_student.parquet
Saved metadata: C:\Users\sobhan\Downloads\HW_A\data\features\listing_availability_features_v1_student_metadata.json
Saved validation report: C:\Users\sobhan\Downloads\HW_A\data\features\listing_availability_features_v1_student_validation_report.json
Saved PII audit: C:\Users\sobhan\Downloads\HW_A\data\features\pii_audit_v1_student.csv

## 17. Final preview

Use this final cell to confirm the output shape and columns.

Before moving to Notebook 2, make sure:

- target column exists,
- model input columns do not include future columns,
- no forbidden PII columns are present,
- saved files exist in `data/features/`.

In [116]:
print("Final shape:", feature_df.shape)

display(feature_df.head())

feature_df.info()

Final shape: (10480, 32)

,listing_id,room_type,property_type,accommodates,bedrooms,beds,bathrooms,listing_price,minimum_nights,maximum_nights,...,avg_maximum_nights_calendar_history,available_days_last_30d,available_rate_last_30d,future_calendar_days_observed_30d,future_available_days_30d,future_available_rate_30d,high_demand_proxy,cutoff_date,dataset_version,has_reviews
0,27886,Private room,Private room in houseboat,2,1.0,1.0,1.5,132.0,3,356,...,30.0,0,0.000000,30,0,0.0,1,2026-08-11,v1_student,1
1,28871,Private room,Private room in rental unit,2,1.0,1.0,1.0,89.0,2,730,...,730.0,14,0.466667,30,21,0.7,0,2026-08-11,v1_student,1
2,29051,Private room,Private room in condo,2,1.0,1.0,1.0,61.0,2,730,...,730.0,16,0.533333,30,0,0.0,1,2026-08-11,v1_student,1
3,44391,Entire home/apt,Entire rental unit,4,2.0,NaN,1.5,NaN,3,730,...,730.0,0,0.000000,30,0,0.0,1,2026-08-11,v1_student,1
4,48373,Entire home/apt,Entire rental unit,4,2.0,NaN,1.5,NaN,3,1125,...,1125.0,0,0.000000,30,0,0.0,1,2026-08-11,v1_student,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10480 entries, 0 to 10479
Data columns (total 32 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   listing_id                           10480 non-null  int64
 1   room_type                            10480 non-null  object
 2   property_type                        10480 non-null  object
 3   accommodates                         10480 non-null  int64
 4   bedrooms                             10174 non-null  float64
 5   beds                                 5904 non-null   float64
 6   bathrooms                            10468 non-null  float64
 7   listing_price                        5874 non-null   float64
 8   minimum_nights                       10480 non-null  int64
 9   maximum_nights                       10480 non-null  int64
 10  instant_bookable                     10480 non-null  bool
 11  is_superhost                         10365 non-null  boolean
 12  host_listing_count                   10480 non-null  int64
 13  neighbourhood_name                   10480 non-null  object
 14  total_reviews_before_cutoff          10480 non-null  float64
 15  unique_reviewers_before_cutoff       10480 non-null  float64
 16  avg_comment_len_before_cutoff        9383 non-null   float64
 17  max_comment_len_before_cutoff        9383 non-null   float64
 18  days_since_last_review               10480 non-null  float64
 19  available_days_history               10480 non-null  int64
 20  available_rate_history               10480 non-null  float64
 21  avg_minimum_nights_calendar_history  10480 non-null  float64
 22  avg_maximum_nights_calendar_history  10480 non-null  float64
 23  available_days_last_30d              10480 non-null  int64
 24  available_rate_last_30d              10480 non-null  float64
 25  future_calendar_days_observed_30d    10480 non-null  int64
 26  future_available_days_30d            10480 non-null  int64
 27  future_available_rate_30d            10480 non-null  float64
 28  high_demand_proxy                    10480 non-null  int32
 29  cutoff_date                          10480 non-null  datetime64[ns]
 30  dataset_version                      10480 non-null  object
 31  has_reviews                          10480 non-null  int32
dtypes: bool(1), boolean(1), datetime64[ns](1), float64(14), int32(2), int64(9), object(4)
memory usage: 2.3+ MB